// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVcThueG3QcvkrpiWNmlfr59T66zdac88',
    appId: '1:1017814825771:web:bfd3d4218a4e4e9c73236e',
    messagingSenderId: '1017814825771',
    projectId: 'aura-9b811',
    authDomain: 'aura-9b811.firebaseapp.com',
    storageBucket: 'aura-9b811.firebasestorage.app',
    measurementId: 'G-XSYN6MWN62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeOlVv-u00agSJz5GO_mgmGQ1X-qNs13Q',
    appId: '1:1017814825771:android:795fcc83140e919273236e',
    messagingSenderId: '1017814825771',
    projectId: 'aura-9b811',
    storageBucket: 'aura-9b811.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKWGFd-FsRqc0mg20iLZvVk79BPM7MFz4',
    appId: '1:1017814825771:ios:2848989f4ddce0ec73236e',
    messagingSenderId: '1017814825771',
    projectId: 'aura-9b811',
    storageBucket: 'aura-9b811.firebasestorage.app',
    iosBundleId: 'com.example.aura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKWGFd-FsRqc0mg20iLZvVk79BPM7MFz4',
    appId: '1:1017814825771:ios:2848989f4ddce0ec73236e',
    messagingSenderId: '1017814825771',
    projectId: 'aura-9b811',
    storageBucket: 'aura-9b811.firebasestorage.app',
    iosBundleId: 'com.example.aura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVcThueG3QcvkrpiWNmlfr59T66zdac88',
    appId: '1:1017814825771:web:cffb26ba8526e69e73236e',
    messagingSenderId: '1017814825771',
    projectId: 'aura-9b811',
    authDomain: 'aura-9b811.firebaseapp.com',
    storageBucket: 'aura-9b811.firebasestorage.app',
    measurementId: 'G-G168YPS8EK',
  );
}
